#!/bin/bash

# Metadata
# Script Name: AWS Resource Report
# Author: Your Name
# Version: 1.0
# Date: April 15, 2024

# Function to get EC2 instance details
get_ec2_instances() {
    echo "===== EC2 Instances ====="
    aws ec2 describe-instances --query 'Reservations[*].Instances[*].[InstanceId,InstanceType,State.Name,PrivateIpAddress,PublicIpAddress,Tags[?Key==`Name`].Value]' --output table
}

# Function to get IAM user details
get_iam_users() {
    echo "===== IAM Users ====="
    aws iam list-users --query 'Users[*].[UserName,UserId,CreateDate]' --output table
}

# Function to get S3 bucket details
get_s3_buckets() {
    echo "===== S3 Buckets ====="
    aws s3api list-buckets --query 'Buckets[*].[Name,CreationDate]' --output table
}

# Main function to call other functions
main() {
    echo "========================================"
    echo "AWS Resource Report - Version 1.0"
    echo "Report generated on: $(date)"
    echo "Report generated by: Mohsinkamaal Mulla"
    echo "========================================"
    get_ec2_instances
    get_iam_users
    get_s3_buckets
}

# Execute the main function
main

